spring:
  application:
    name: pruebalegoback
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/clinicdb
    username: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver

app:
  context: ${APP_CONTEXT:/api}
# VAR_application_yml_self_app_configuration_opt

# VAR_application_yml_self_app_security_configuration_opt


