weather:
  api:
    url: "https://api.open-meteo.com/v1/gfs?latitude=37.7749&longitude=-122.4194&hourly=temperature_2m,precipitation,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&current=temperature_2m,precipitation&forecast_days=3&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=America/Los_Angeles"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  application:
    name: pruebalegoback
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/clinicdb
    username: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver

app:
  context: ${APP_CONTEXT:/api}
# VAR_application_yml_self_app_configuration_opt

# VAR_application_yml_self_app_security_configuration_opt

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.example.demo: DEBUG
  file:
    name: logs/webflux-demo.log
